import { ReferentielPhysique } from "../referentiel-physique/referentiel-physique";

export interface SignaletiquePhysique {
    idUniqueReferentiel : string,
    civilite : ReferentielPhysique,
    genre : ReferentielPhysique,
    situationfamiliale : ReferentielPhysique,
    certification : ReferentielPhysique,
    regime: ReferentielPhysique,
    libNomUsuel:string,
    libPrenomUsuel: string,
    libNomNaissance:string,
    libPrenomNaissance:string,
    dateNaissance: Date,
    libNomMarital:string,
    libLieuNaissance: string,
    catacteur:ReferentielPhysique,
    libPaysNaissance:string,
    codePostalNaissance:string,
    codeDepartNaissance:string,
    noNir:string,
    codeCleNir:string,
    codeComplementNir:string,
    noTelBureau:string,
    noTelDomicile:string,
    noTelPortable:string,
    noFax:string,
    libEmail:string,
    indProtege:string,
    indSensible:string,
    indVip:string,
    indAdministrateur:string,
    indDeces:string,
    dateDeces:string,
    idSystemSrc:string,
    idRefOrig:string,
    dathMajRef:string,
    dathChargEpref:string,
    dateTrtMajEpref:string

}